version: "3.9"

services:
  app:
    container_name: project1-container
    image: project1-container
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgresqldb

  postgresqldb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=daniel1
      - POSTGRES_DB=reimbursementapi